# Generated by Django 3.2.23 on 2024-01-10 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HasilPemeriksaan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hpid', models.CharField(max_length=100)),
                ('id_pemeriksaan', models.CharField(max_length=100)),
                ('nama_uji_lab', models.CharField(max_length=100)),
                ('hasil', models.CharField(max_length=100)),
                ('satuan', models.CharField(max_length=100)),
                ('nilai_normal', models.CharField(max_length=50)),
            ],
        ),
    ]
