# Generated by Django 3.2.23 on 2023-11-26 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UjiLab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=100)),
                ('users', models.CharField(max_length=50)),
                ('diagnosa_awal', models.CharField(max_length=250)),
                ('tanggal_pemeriksaan', models.DateField()),
                ('testers', models.CharField(max_length=50)),
            ],
        ),
    ]
