# Generated by Django 3.2.23 on 2024-01-04 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=100)),
                ('nama', models.CharField(max_length=150)),
                ('pemeriksaan_on_proses', models.CharField(max_length=100)),
                ('pemeriksaan_selesai', models.CharField(max_length=100)),
                ('total_pemeriksaan', models.CharField(max_length=100)),
            ],
        ),
    ]
