# Generated by Django 3.2.23 on 2024-01-04 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NilaiNormal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idn', models.CharField(max_length=50)),
                ('id_uji_lab', models.CharField(max_length=50)),
                ('nilai_normal', models.CharField(max_length=100)),
                ('nama_pemeriksaan', models.CharField(max_length=150)),
                ('kategori', models.CharField(max_length=150)),
                ('jenis_kelamin', models.CharField(max_length=50)),
                ('satuan', models.CharField(max_length=150)),
            ],
        ),
    ]
