# Generated by Django 3.2.23 on 2024-01-02 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dokter',
            name='komisi_dokter',
            field=models.IntegerField(default=0),
        ),
    ]
